generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: pi-hole.net
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct  6 04:50:35 2026 GMT
  hsts: false
- host: docs.pi-hole.net
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 21 16:53:46 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: pi.hole
  https: false
domains:
- domain: pi-hole.net
  dnssec: false
  caa:
  - 0 issue "sectigo.com"
  - 0 iodef "mailto:servers@pi-hole.net"
  - 0 issuewild "letsencrypt.org"
  - 0 issue "letsencrypt.org"
  - 0 issuewild "sectigo.com"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
- domain: pi.hole
  dnssec: false
  caa: []
  spf: false
  dmarc: false
